### ISSUE TITLE
CS1010S 2014 Apr Qn 2D

### ISSUE THREAD

**Issue by pakshuang** [RussellDash332/cs1010s-finals-template#1]
I can help add a test case (using `update_inventory(wands)(4)`) or is it intentionally left out because `update_inventory(wands)(4)` is the solution to the next question?

https://github.com/RussellDash332/cs1010s-finals-template/blob/af23b0fa689724ad530614666b2ff60c5e10bd6d/CS1010S/cs1010s-apr14-template.py#L46-L48

**Comment by RussellDash332** [comment]
Yes. It is not given because it's the same thing as 2E.
